### PR TITLE
Fix: added auto_increment to sql dump

### LINKED ISSUE #306: adding a module
I cloned this project from git and set up a db and git keys. 
Now I try to add a module from Github and get a sql error.
"Statement could not be executed (23000 - 1048 - Column 'module_id' cannot be null)"

This is an insert statement and I believe module_id column should be auto-increment. This isn't the case if you use the .sql file in the git. 

The module mapper's insert looks like this. What's up??
 $result = parent::insert($entity, $tableName, $hydrator);
        $entity->setId($result->getGeneratedValue());
        return $result;

### PR DESCRIPTION
**Pull request by ins0**
fixes #306 

and #251 can be closed?

### CODE REVIEW

**Comment by localheinz** [comment]
@ins0 

Looks good to me, but since @GeeH deploys, I think he should have a look!

**Comment by localheinz** [comment]
@GeeH 

If we merge this, how are you going to make the changes to the database? Manually? Since we decided against #252, shall we maybe use http://phinx.org?

**Comment by localheinz** [comment]
@ins0 

I'm happy to merge this so I could remove this workaround in a test

* https://github.com/localheinz/modules.zendframework.com/blob/feature/search/module/ZfModule/test/ZfModuleTest/Integration/Mapper/ModuleTest.php#L176-L191

however, my concerns in https://github.com/zendframework/modules.zendframework.com/pull/340#issuecomment-73226042 are still valid, no?

**Comment by ins0** [comment]
as the page was working (adding/removing) repositorys and the ``state`` bug was fixed too before this PR, the database should be allready in this format and could be safely merged. no?

**Comment by localheinz** [comment]
@ins0 

I have no idea, I don't have access to the production system.

@GeeH 

Can you confirm that the @ins0 statements are true for the production system?

**Comment by localheinz** [comment]
Confirming that the database schema in production is up-to-date with this, and merging.

Thank you, @ins0!

**Comment by ins0** [comment]
i love your server access :dancers:  - thanks!

**Comment by gianarb** [comment]
giphy

**Comment by localheinz** [comment]
@gianarb 

:smile:

**Pull request merged**
