### PR TITLE
Fix: organizationAction() should be listAction()

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] renames `Controller\IndexController::organizationAction()` to `listAction()` because that's what is in the route name, and also, what the action does, that is, list modules

:bulb: Controller should probably be named differently as well, e.g., `ModuleController`

### CODE REVIEW

**Comment by Ocramius** [comment]
Requires rebasing

**Comment by localheinz** [comment]
@Ocramius 

Rebased, thank you for reviewing!

**Comment by Ocramius** [comment]
:+1:

**Comment by localheinz** [comment]
Thank you, @Ocramius!

**Pull request merged**
