### PR TITLE
Enhancement: Use doctrine/migrations to modify the database schema

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] requires `doctrine/doctrine-module`
* [x] requires `doctrine/doctrine-orm-module`
* [x] requires `doctrine/migrations`
* [x] adds a basic configuration for the `DoctrineORMModule` (minimum required for migrations)
* [x] enables both `DoctrineModule` and `DoctrineORMModule`
* [x] extracts a migration from `data/sql/0.sql`
* [x] uses migrations to set up database in tests
* [x] removes the database dump
* [x] adds a test case for migrations
* [x] moves migrations into `Application` namespace
* [x] updates build target to run migrations in production, too

Related to #497.

:information_desk_person: The Doctrine console commands are available via

```
$ php public/index.php
```

Enjoy!

### CODE REVIEW

**Comment by localheinz** [comment]
@ins0 @Ocramius 

Have a look at this! :smiley:

**Comment by gianarb** [comment]
This is a hight priority respect #497 

And it is ready to go!! :)

**Comment by Ocramius** [comment]
Needs a rebase, sadly :-(

**Comment by gianarb** [comment]
bad day

**Comment by localheinz** [comment]
@gianarb @Ocramius 

Done! :relaxed:

**Comment by gianarb** [comment]
wowowo!!!! :balloon:

**Comment by Ocramius** [comment]
:+1:

**Pull request merged**
