### PR TITLE
Feature: Update complete page to Bootstrap 3

### PR DESCRIPTION
**Pull request by ins0**
- fixes many nasty html structures/pyramides
- jumps to a maintained bootstrap version
- smooth mobile support

follows #369
implements minor style suggestions from #305

### CODE REVIEW

**Comment by ins0** [comment]
i tried to make the page look like the current one but with the new bootstrap version this is not 100% equal.

**Comment by Ocramius** [comment]
@ins0 it doesn't need to be 100% equal

**Comment by localheinz** [comment]
@ins0 

Cool! Current design feels a bit outdated!

**Comment by Ocramius** [comment]
Merging because yolo! Thanks @ins0!

**Comment by ins0** [comment]
thanks @Ocramius

**Pull request merged**
