### PR TITLE
Fix: Removed unused methods inside ViewHelpers

### PR DESCRIPTION
**Pull request by ins0**
This removes unused methods inside the viewhelper

### CODE REVIEW

**Comment by localheinz** [comment]
@Ocramius 

Shall I have a look?

**Comment by Ocramius** [comment]
@localheinz ok, assigning it to you, but please check that the prod site is running first.

**Comment by localheinz** [comment]
Will do, @Ocramius !

**Comment by localheinz** [comment]
@GeeH 

I think the production site is running ok, you just mentioned it a second ago!

**Pull request merged**
