### PR TITLE
Change composer autoload to psr-4

### PR DESCRIPTION
**Pull request by gianarb**
Update composer autoload to psr-4

### CODE REVIEW

**Comment by Ocramius** [comment]
The project is PSR-0 based, why would you complicate the autoloader just for the sake of switching to PSR-4? :|

**Comment by gianarb** [comment]
> Deprecated - As of 2014-10-21 PSR-0 has been marked as deprecated. PSR-4 is now recommended as an alternative.
> [php-fig](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md)

**Comment by Ocramius** [comment]
After discussion on gtalk, I decided that this should be mergeable. @gianarb please rebase.

**Comment by gianarb** [comment]
ping @Ocramius thanks!

**Comment by Ocramius** [comment]
:+1:

**Comment by gianarb** [comment]
Thanks @Ocramius

**Pull request merged**
