### PR TITLE
[WIP] Fix: Regular expression in route definition

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds a failing test, asserting the route doesn't match if the user name is invalid
* [x] fixes a config key which should be `constraints` instead of `constrains`
* [ ] fixes the regular expression for the route match with the feedback of @Ocramius and @ins0 

Follows #444.

### CODE REVIEW

**Comment by localheinz** [comment]
@gianarb @ins0 @Ocramius 

In regard to this, it seems we've got a few more unresolved issues, see the reason for the failing test above:

* https://travis-ci.org/zendframework/modules.zendframework.com/jobs/53197200#L286

**1. There are more routes which would need the same constraints**

```php
'view-module' => [
    'type'    => 'Segment',
    'options' => [
        'route'    => '/:vendor/:module',
        'defaults' => [
            'controller' => Controller\IndexController::class,
            'action'     => 'view',
        ],
        // constraints required here
        'constraints' => [
            'vendor' => '[a-zA-Z][a-zA-Z0-9_-]*', // same regular expression required here
            'module' => '', // some regular expression required here
        ],
    ],
],
```

```php
'zf-module'   => [
    'type'          => 'Segment',
    'options'       => [
        'route'    => '/module',
        'defaults' => [
            'controller' => Controller\IndexController::class,
            'action'     => 'index',
        ],
    ],
    'may_terminate' => true,
    'child_routes'  => [
        'list'   => [
            'type'    => 'Segment',
            'options' => [
                'route'      => '/list[/:owner]',
                'constrains' => [ // should be constraints, by the way
                    'owner' => '[a-zA-Z][a-zA-Z0-9_-]*', // same regular expression required here
                ],
                'defaults'   => [
                    'action' => 'organization',
                ],
            ],
        ],
    ],
],
```

** 2. Yes, there is a user named `user`

Right here, there he is: https://github.com/user

**Comment by gianarb** [comment]
Exist also `module` username :P

**Comment by ins0** [comment]
https://github.com/zendframework/modules.zendframework.com/pull/444#discussion_r25733105 covers the username format but i feel uncomfortable writing such regex everytime we need a username in the url :smiley:

**Comment by localheinz** [comment]
@gianarb 

True, here she is: https://github.com/module!

**Comment by localheinz** [comment]
@ins0 @gianarb 

I'd prefer to extract a constant here, what do you guys think?

**Comment by ins0** [comment]
``vendor`` => ``^(?!.*--.*)([a-zA-Z0-9][a-zA-Z0-9-]+?[a-zA-Z0-9])$|(^[a-zA-Z0-9]+$)``
``module`` => ``^(?![^a-zA-Z0-9.\-_])[a-zA-Z0-9.\-_]+$``

> I'd prefer to extract a constant here,
don't not know really what you mean

**Comment by localheinz** [comment]
@ins0 

I would define constants containing the regular expressions, then refer to these constants in the route definitions to avoid duplication.

**Comment by ins0** [comment]
:+1:

**Comment by GeeH** [comment]
Please rebase this onto `develop` branch.

**Pull request closed without merging**
