### PR TITLE
Fix phpdocs

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by ins0** [comment]
the current comments are inline ``/*`` but the suggested would be docblock `/**``  comments. so the current comment should be fine. no?

**Comment by localheinz** [comment]
PHPStorm's intention adds `/**`, but `/*` is sufficient for inline comments, I believe.

**Comment by Ocramius** [comment]
Note that `/**` is a docblock comment, not a normal comment. Don't use it except for docblocks

**Comment by GeeH** [comment]
The comments are correct as they are `/*` is right.

**Pull request closed without merging**
