### PR TITLE
Remove composer minimum stability

### PR DESCRIPTION
**Pull request by snapshotpl**
With composer minimum stabilty dev:
* zf and many others is loaded from master (unstable),
* loading time from branch (no tag) it's sooooo long...

### CODE REVIEW

**Comment by localheinz** [comment]
:+1: for also actually pinning to concrete versions, unless necessary to pin to a branch.

**Comment by GeeH** [comment]
Have you tested this? I would expect a corrisponding `composer.lock` update (unless this doesn't change loaded versions).

**Comment by snapshotpl** [comment]
Everything working fine: manual and unit tests. I see a huge different in speed when I run `composer install` becouse with stable option composer download from tag (zip), without stable download from branch.

**Comment by GeeH** [comment]
:+1: 

Thanks for your time :)

**Pull request merged**
