### PR TITLE
Fix: composer.lock is not up to date, build issues

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] updates an out-of-date `composer.lock` by running `$ composer update`
* [x] fixes an unrelated CS issue which caused the build to break
* [x] fixes an issue where dependencies on Travis are updated, instead of being installed
* [x] self-updates composer in the `before_install` section (see http://till.klampaeckel.de/blog/archives/204-Whats-wrong-with-composer-and-your-.travis.yml.html, h/t @till)

### CODE REVIEW

**Comment by localheinz** [comment]
Related to https://github.com/zendframework/modules.zendframework.com/pull/394, where the build currently fails, however, not related to any changes made therein.

See https://travis-ci.org/zendframework/modules.zendframework.com/jobs/51290091#L270.

**Comment by localheinz** [comment]
Actually, I'm not even sure if this is the right approach for making sure the **right** dependencies are installed on Travis:

* https://travis-ci.org/zendframework/modules.zendframework.com/jobs/51290091#L107
* https://github.com/zendframework/modules.zendframework.com/blob/master/.travis.yml#L16

Should only install, in my opinion!

**Comment by Ocramius** [comment]
@localheinz merged, thanks!

**Comment by localheinz** [comment]
Thank you, @Ocramius!

**Pull request merged**
