### PR TITLE
HOTFIX: changed github api call order

### PR DESCRIPTION
**Pull request by ins0**
as explained here https://github.com/EvanDotPro/EdpGithub/issues/23

the markdown request (POST) needs to be called last as it destroys the normal requests

### CODE REVIEW

**Comment by Ocramius** [comment]
Weird bug. Merging as there is no meaningful way to test this here: should be fixed in EdpGithub instead.

**Comment by ins0** [comment]
thanks @Ocramius - so fast that the travis build failed :speedboat:

**Comment by Ocramius** [comment]
Grey builds all the things

**Comment by ins0** [comment]
:smiling_imp:

**Pull request merged**
