### PR TITLE
Fixed forgot chapter

### PR DESCRIPTION
**Pull request by gianarb**
Vagrant at the moment is not supported

### CODE REVIEW

**Comment by Ocramius** [comment]
Huh? Since when? :|

**Comment by gianarb** [comment]
We removed phpuppet a lot of time ago :)

**Comment by Ocramius** [comment]
Yeah, and there's no Vagrant support at all now? Like, not even with simple bash provisioning? Can we at least fix that? Of course people won't be able to contribute otherwise :|

**Comment by gianarb** [comment]
Ok I build a slim solution.

Close #504

2015-10-18 21:01 GMT+02:00 Marco Pivetta <notifications@github.com>:

> Yeah, and there's no Vagrant support at all now? Like, not even with
> simple bash provisioning? Can we at least fix that? Of course people won't
> be able to contribute otherwise :|
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zendframework/modules.zendframework.com/pull/504#issuecomment-149039203>
> .
>



-- 
Gianluca Arbezzano
www.gianarb.it

**Pull request closed without merging**
